### ISSUE TITLE
Incorporate Slack Invite Automation

### ISSUE THREAD

**Issue by anguyen88** [phldesign/phldesign.github.io#4]
Integrate someting like…
https://github.com/outsideris/slack-invite-automation

To automate inviting members to the PHLDesign Slack

**Comment by pixelyunicorn** [comment]
You should take a look at https://github.com/rauchg/slackin, used by phillydev.org:

![image](https://cloud.githubusercontent.com/assets/607807/8362819/2015ae76-1b49-11e5-8ab5-f497502b1a50.png)
